on:
  push:
    branches:
      - master
      - staging
      - dev

jobs:
  build:
    environment: 
      name: development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Expose project info
        run: |
          echo "PROJECT_NAME=`jq -r '.name' ./documentation/project_info.json`" >> $GITHUB_ENV
          echo "PROJECT_VERSION=`jq -r '.version' ./documentation/project_info.json`" >> $GITHUB_ENV
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> .npmrc
          echo "@extrahorizon:registry=https://npm.pkg.github.com" >> .npmrc
          
        env:
         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
         GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_FULL_READ_ACCESS_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: '@extrahorizon'

      - name: Transpile & publish
        run: |
          yarn
          # yarn test --> replace
          yarn build
          yarn --production

          # Package
          zip build.zip -rqX build node_modules .env.example
          
          # Deploy
          aws lambda update-function-code --region $AWS_REGION --function-name $PROJECT_NAME --zip-file fileb://$PWD/build.zip > /dev/null
          
          echo "${PROJECT_NAME} updated successfully to ${AWS_REGION}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1